logger:
  enable: true
  pretty_backtrace: false
  level: info
  format: json
  override_filter: null
  file_appender: null

server:
  binding: 0.0.0.0
  port: 8080
  host: http://127.0.0.1
  ident: STDAS Gateway
  middlewares:
    limit_payload:
      enable: true
      body_limit: 5mb
    logger:
      enable: true
    catch_panic:
      enable: true
    timeout_request:
      enable: true
      timeout: 5000
    compression:
      enable: true
    cors:
      enable: true

cache:
  kind: Null

queue: null
auth: null
workers:
  mode: BackgroundAsync
mailer: null
initializers: null
scheduler: null
settings: null
