logger:
  enable: false
  pretty_backtrace: false
  level: error
  format: compact
  override_filter: null
  file_appender: null

server:
  binding: 127.0.0.1
  port: 0
  host: http://127.0.0.1
  ident: STDAS Gateway
  middlewares:
    limit_payload:
      enable: true
      body_limit: 5mb
    logger:
      enable: false
    catch_panic:
      enable: true
    timeout_request:
      enable: true
      timeout: 5000
    compression:
      enable: false
    cors:
      enable: true

cache:
  kind: Null

queue: null
auth: null
workers:
  mode: ForegroundBlocking
mailer: null
initializers: null
scheduler: null
settings: null
